In [ ]:
print( 'Name:- Dhiyanesh Babu C V \nReg no:- 19MID0125\nDataset:- iris dataset\n\nHere we have implenented multiclass svm classification\n The dependent variable [ SPECIES ] is found using 4 independent variables such as [ Sepallength, sepalwidth, petallength, petalwidth ]\nisHere  we have used 5 types of kernels namely.\n1.)RBF\n2.)Poly\n3.)Linear\n4.)Sigmoid\n5.)precomputed\n')






Name:- Dhiyanesh Babu C V 
Reg no:- 19MID0125
Dataset:- iris dataset

Here we have implenented multiclass svm classification
 The dependent variable [ SPECIES ] is found using 4 independent variables such as [ Sepallength, sepalwidth, petallength, petalwidth ]
isHere  we have used 5 types of kernels namely.
1.)RBF
2.)Poly
3.)Linear
4.)Sigmoid
5.)precomputed



In [ ]:
# importing necessary modules

from sklearn import svm
import sklearn.model_selection as model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
# Loading the dataset

iris = pd.read_csv('IRIS.csv')

In [ ]:
# Splitting the dataset into dependent and independent

x = iris[['sepal_length','sepal_width','petal_length','petal_width']]
y=iris[['species']]

In [ ]:
# Splitting the dataset into traina nd test set

X_train, X_test, Y_train, Y_test=train_test_split(x,y,test_size = 0.4, random_state=0)

In [ ]:
# choice of kernel

print('The available choices are linear, rbf, sigmoid, poly, precomputed ')
choice = str(input())

The available choices are linear, rbf, sigmoid, poly, precomputed 
rbf


In [ ]:
# Training the model with respect to the choice of kernel

if choice == 'precomputed':
  
  classifier = svm.SVC(kernel = 'precomputed', random_state = 0)
  kernel_train=np.dot(X_train,X_train.T)
  kernel_test=np.dot(X_test,X_train.T)
  classifier.fit(kernel_train, Y_train.values.ravel())
  y_pred = classifier.predict(kernel_test)
  linear_con = confusion_matrix(Y_test,y_pred)
  print('Confusion matrix of precomputed kernel')
  print(linear_con)
  linear_accur = accuracy_score(Y_test, y_pred)
  linear_f1= f1_score(Y_test, y_pred,average = 'weighted')
  print('Accuracy of precomputed kernel')
  print(linear_accur)
  print('F1 score of precomputed kernel')
  print(linear_f1)

else:
  linear=svm.SVC(kernel= choice ).fit(X_train,Y_train.values.ravel())
  linear_pred = linear.predict(X_test)
  linear_con = confusion_matrix(Y_test,linear_pred)
  print('confusion matrix of '+ choice +' kernel is')
  print(linear_con)
  print('\n')
  linear_accur = accuracy_score(Y_test, linear_pred)
  linear_f1= f1_score(Y_test, linear_pred,average = 'weighted')
  print('Accuracy of '+ choice +' kernel is')
  print(linear_accur)
  print('\n')
  print('F1 score of '+ choice +' kernel is')
  print(linear_f1)

confusion matrix of rbf kernel is
[[16  0  0]
 [ 0 22  1]
 [ 0  3 18]]


Accuracy of rbf kernel is
0.9333333333333333


F1 score of rbf kernel is
0.9330555555555555
